export declare interface IPlatform {
  init()
  login()
  getUserinfo(callback)
  createUserInfoButton(successCallback)
  createBannerAd()
  showBannerAd()
  hideBannerAd()
  createRewardedVideoAd()
  showRewardedVideoAd(callback)
  hideRewardedVideoAd()
  createInterstitialAd()
  showInterstitial()
  hideInterstitial()
}
