export declare interface IPlatform {
  init()
  login()
  getUserinfo()
  createUserInfoButton(successCallback, errorCallback, target)
  createBannerAd()
  showBannerAd()
  hideBannerAd()
  createRewardedVideodAd()
  showRewardedVideoAd(callback)
  hideRewardedVideoAd()
  createInterstitialAd()
  showInterstitial()
  hideInterstitial()
}
